CREATE TABLE [dbo].[qs_alert] (
    [account] varchar(64) NOT NULL,
    [process_date] datetime2(7) NULL,
    [symbol] varchar(30) NULL,
    [first_message_timestamp] datetime2(7) NOT NULL,
    [last_message_timestamp] datetime2(7) NOT NULL,
    [new_orders] int NOT NULL,
    [updated_orders] int NOT NULL,
    [canceled_orders] int NOT NULL,
    [zscore_total_orders] numeric(18,2) NOT NULL,
    [zscore_otr] numeric(18,2) NOT NULL,
    [zscore_ocr] numeric(18,2) NOT NULL,
    [total_orders] int NOT NULL,
    [otr] numeric(18,2) NOT NULL,
    [ocr] numeric(18,2) NOT NULL,
    [avg_orders] numeric(18,2) NOT NULL,
    [stddev_orders] numeric(18,2) NOT NULL,
    [avg_otr] numeric(18,2) NOT NULL,
    [stddev_otr] numeric(18,2) NOT NULL,
    [avg_ocr] numeric(18,2) NOT NULL,
    [stddev_ocr] numeric(18,2) NOT NULL,
    [recurrent_alert] bit NULL,
    [trades] int NULL
);