CREATE TABLE [dbo].[tb_client_daily_profile] (
    [id] int IDENTITY(1,1) NOT NULL,
    [process_date] date NOT NULL,
    [account] varchar(50) NOT NULL,
    [symbol] varchar(20) NOT NULL,
    [total_orders_sent] int NOT NULL DEFAULT ((0)),
    [total_orders_executed] int NOT NULL DEFAULT ((0)),
    [total_orders_cancelled] int NOT NULL DEFAULT ((0)),
    [total_orders_rejected] int NOT NULL DEFAULT ((0)),
    [cancel_rate_pct] decimal(18,4) NOT NULL DEFAULT ((0)),
    [execution_rate_pct] decimal(18,4) NOT NULL DEFAULT ((0)),
    [total_financial_volume] decimal(18,4) NOT NULL DEFAULT ((0)),
    [buy_volume] decimal(18,4) NOT NULL DEFAULT ((0)),
    [sell_volume] decimal(18,4) NOT NULL DEFAULT ((0)),
    [buy_sell_ratio] decimal(18,4) NOT NULL DEFAULT ((0)),
    [trade_count] int NOT NULL DEFAULT ((0)),
    [avg_ticket] decimal(18,4) NOT NULL DEFAULT ((0)),
    [predominant_time_window] varchar(30) NULL,
    [first_trade_time] time(7) NULL,
    [last_trade_time] time(7) NULL,
    [main_counterparty] varchar(100) NULL,
    [direct_trades_pct] decimal(18,4) NOT NULL DEFAULT ((0)),
    [rlp_trades_pct] decimal(18,4) NOT NULL DEFAULT ((0)),
    [total_alerts_day] int NOT NULL DEFAULT ((0)),
    [created_at] datetime2(7) NOT NULL DEFAULT (getdate()),
    [total_orders_modify] int NULL,
    [modify_rate_pct] decimal(18,4) NULL,
    CONSTRAINT [PK_tb_client_daily_profile] PRIMARY KEY ([id])
);