CREATE TABLE [dbo].[tb_order_osc_hist] (
    [order_key] bigint NOT NULL,
    [order_id] bigint NULL,
    [secondary_order_id] bigint NULL,
    [account] bigint NULL,
    [order_timestamp] datetime2(7) NULL,
    [msg_type] int NULL,
    [party_id] int NULL,
    [price] decimal(17,2) NULL,
    [last_px] decimal(17,2) NULL,
    [quantity] bigint NULL,
    [cumqty] int NULL,
    [lastqty] int NULL,
    [leavesqty] int NULL,
    [side] tinyint NULL,
    [symbol] varchar(30) NULL,
    [exec_type] varchar(32) NULL,
    [ord_status] int NULL,
    [process_date] datetime2(7) NOT NULL,
    [book_timestamp] datetime2(7) NULL,
    [book_spread] decimal(17,2) NULL,
    [order_spread] decimal(17,2) NULL,
    [trade_aggressor] varchar(50) NULL,
    [trade_buying_broker] varchar(50) NULL,
    [trade_id] varchar(50) NULL,
    [trade_price] varchar(50) NULL,
    [trade_selling_broker] varchar(50) NULL,
    [trade_time] varchar(50) NULL,
    [trade_type] varchar(50) NULL,
    [flag_cross] int NULL,
    [flag_recurrence] int NULL,
    CONSTRAINT [PK_tb_order_osc_hist] PRIMARY KEY ([order_key], [process_date])
);

ALTER TABLE [dbo].[tb_order_osc_hist] ADD CONSTRAINT [FK_tb_order_osc_hist_2] FOREIGN KEY ([account], [symbol], [process_date]) REFERENCES [dbo].[tb_account_osc_hist] ([account], [symbol], [process_date]);