CREATE PROCEDURE [dbo].[PR_ATIVARPORTALFIRA]
(
    @PRODUCTKEY VARCHAR(1000), @EXPIRATIONDATE INT
)--WITH ENCRYPTION
AS
BEGIN
    IF NOT EXISTS (SELECT * FROM ATIVACAOPORTALFIRA)
	BEGIN
    INSERT INTO ATIVACAOPORTALFIRA
    VALUES(@PRODUCTKEY, @EXPIRATIONDATE)
	END
	ELSE
	BEGIN
    UPDATE ATIVACAOPORTALFIRA 
	SET CHAVE = @PRODUCTKEY,
	DATAVENCIMENTO = @EXPIRATIONDATE
	END
END